name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --save-exact

      - name: Run ESLint
        run: npm run lint

      - name: Type Check
        run: npm run tsc --noEmit

      - name: Build Project
        run: npm run build
