name: Push Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'npm' 

      - name: Install dependencies
        run: npm install --save-exact

      - name: Run ESLint
        run: npm run lint || true

      - name: Type Check
        run: npm run tsc --noEmit

      - name: Check for public/index.html
        id: check-index
        run: |
          if [ ! -f ./public/index.html ]; then
            echo "index.html not found. Skipping build."
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo "index.html found. Proceeding with build."
            echo "skip_build=false" >> $GITHUB_ENV
          fi

      - name: Build Project
        if: env.skip_build != 'true'
        run: npm run build
        